import { version } from '@magic/test'

import {
  cleanIpAddress,
  createServer,
  createSecureContext,
  denyRequest,
  enhanceRequest,
  etags,
  getClientIp,
  getCurrentDate,
  getFileEncoding,
  getHostCertificates,
  getHostname,
  getRandomId,
  getRequestDuration,
  getProxies,
  isSendableFile,
  formatLog,
  respond,
  sendFile,
  sendStream,
  body,
  clientError,
  listener,
} from '../src/index.js'

const commons = {
  cleanIpAddress,
  createServer,
  createSecureContext,
  denyRequest,
  enhanceRequest,
  etags,
  getClientIp,
  getCurrentDate,
  getFileEncoding,
  getHostCertificates,
  getHostname,
  getRandomId,
  getRequestDuration,
  getProxies,
  isSendableFile,
  formatLog,
  respond,
  sendFile,
  sendStream,

  body,
  clientError,
  listener,
}

const spec = {
  cleanIpAddress: 'fn',
  createSecureContext: 'fn',
  createServer: 'fn',
  denyRequest: 'fn',
  enhanceRequest: 'fn',
  etags: 'fn',
  formatLog: 'fn',
  getClientIp: 'fn',
  getCurrentDate: 'fn',
  getFileEncoding: 'fn',
  getHostCertificates: 'fn',
  getHostname: 'fn',
  getProxies: 'fn',
  getRandomId: 'fn',
  getRequestDuration: 'fn',
  isSendableFile: 'fn',
  respond: 'fn',
  sendFile: 'fn',
  sendStream: 'fn',

  body: 'function',
  clientError: 'function',
  listener: 'function',
}

export default version(commons, spec)
